### ISSUE TITLE
How to get the current playback progress？

### ISSUE THREAD

**Issue by Pikdays** [infodevelop/iOSInfoChart#4]

**Comment by heoseongjin** [comment]
iOSInfoChart is implemented to deliver data to the chart at regular intervals through `RealTimeDataHandler`.

First of all, 'getting the current playback progress' is understood as trying to know how much enqueued data has been dequeued. There is also a way to check the `mainQueue` inside the `RealTimeDataHandler`, but I want you to know that iOSInfoChart is for charting real time incoming data.
